# Generated by Django 4.1.3 on 2022-11-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_video_video_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_id",
            field=models.CharField(default="temp", max_length=100),
            preserve_default=False,
        ),
    ]
