# Generated by Django 4.1.3 on 2022-11-20 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_summary_video_has_summary_delete_topic_summary_video"),
    ]

    operations = [
        migrations.RenameField(
            model_name="summary", old_name="end_timestamp", new_name="end",
        ),
        migrations.RenameField(
            model_name="summary", old_name="start_timestamp", new_name="start",
        ),
        migrations.RenameField(
            model_name="summary", old_name="content", new_name="text",
        ),
        migrations.AlterField(
            model_name="summary",
            name="video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="summaries",
                to="core.video",
            ),
        ),
    ]
